-- KoraPay webhook audit/idempotency log.
CREATE TABLE IF NOT EXISTS public.korapay_webhook_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event text NOT NULL,
  reference text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  response jsonb,
  outcome text,
  processed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (event, reference)
);

ALTER TABLE public.korapay_webhook_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service role manages korapay webhook events" ON public.korapay_webhook_events;
CREATE POLICY "service role manages korapay webhook events"
  ON public.korapay_webhook_events
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');
